#!/bin/bash
cd "$(dirname "$(realpath "$0")")"/ # <-- CD into the directory that this script is in
source ../env

# Run
echo "--- START: [$(date '+%Y-%m-%d %H:%M:%S')] $1 ---"

mkdir -p .tmp/
$py3 ingest.py

# Send Ideology Scores to Database table
$py3 "digest.py"

# Make Plots
cd R
Rscript "create_dotplot.R"
cd ..

rm -r .tmp/

## Add Timestamp
echo "--- FIN: [$(date '+%Y-%m-%d %H:%M:%S')] $1 ---"
echo "============"