# Generated by Zappa
# Note: Environment variables are set via Lambda configuration, not here
# This file is loaded by the Zappa handler at runtime

APP_MODULE = "app.backend.routes.routes"
APP_FUNCTION = "app"
EXCEPTION_HANDLER = None
DEBUG = True
LOG_LEVEL = "DEBUG"
BINARY_SUPPORT = True
CONTEXT_HEADER_MAPPINGS = {}
DOMAIN = None
BASE_PATH = None
# Environment variables are configured in Lambda, not committed to repo
ENVIRONMENT_VARIABLES = {}
API_STAGE = "dev"
PROJECT_NAME = "legislator-sear"
SETTINGS_FILE = None
DJANGO_SETTINGS = None
AWS_EVENT_MAPPING = {}
AWS_BOT_EVENT_MAPPING = {}
COGNITO_TRIGGER_MAPPING = {}
ASYNC_RESPONSE_TABLE = ""
ADDITIONAL_TEXT_MIMETYPES = []
